language: android
jdk: openjdk11

branches:
  only:
    - f-droid

script: "./gradlew clean assembleDebug"

android:
  components:
      - platform-tools
      - tools
      - build-tools-28.0.3
      - android-28
      - extra-android-m2repository
